name: anime
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  html: ^0.15.4
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
